# Compound Class and Mechanism of Action

In [1]:
from IPython.display import display

from zebrafish_notebook_utils import (
    build_compound_standardization_map,
    build_mechanism_of_action_alias_map,
    configure_full_dataframe_display,
    load_compound_classification,
)

In [2]:
configure_full_dataframe_display()

compound_name_map_df = build_compound_standardization_map()
display(compound_name_map_df)

                   compound_name   standardized_compound_name     normalized_compound_name mapping_source
0            rs tetrazol glycine  (RS)-(Tetrazol-5-yl)glycine          rs tetrazol glycine          alias
1                            rst  (RS)-(Tetrazol-5-yl)glycine                          rst          alias
2    (RS)-(Tetrazol-5-yl)glycine  (RS)-(Tetrazol-5-yl)glycine                      glycine      canonical
3          4 aminophenyl sulfone        4-Aminophenyl sulfone        4 aminophenyl sulfone          alias
4            aminophenyl sulfone        4-Aminophenyl sulfone          aminophenyl sulfone          alias
5          4-Aminophenyl sulfone        4-Aminophenyl sulfone        4 aminophenyl sulfone      canonical
6                4 aminopyridine              4-aminopyridine              4 aminopyridine          alias
7                            4ap              4-aminopyridine                          4ap          alias
8                4-aminopyridine              4-aminopyridine              4 aminopyridine      canonical
9                  aminophylline                Aminophylline                aminophylline          alias
10                 Aminophylline                Aminophylline                aminophylline      canonical
11                amitripityline                Amitriptyline               amitripityline          alias
12                 amitriptyline                Amitriptyline                amitriptyline          alias
13                 Amitriptyline                Amitriptyline                amitriptyline      canonical
14                     amoxapine                    Amoxapine                    amoxapine          alias
15                     amoxipine                    Amoxapine                    amoxipine          alias
16                     Amoxapine                    Amoxapine                    amoxapine      canonical
17                   amphetamine                  Amphetamine                  amphetamine          alias
18                   Amphetamine                  Amphetamine                  amphetamine      canonical
19                   apomorphine                  Apomorphine                  apomorphine          alias
20                   Apomorphine                  Apomorphine                  apomorphine      canonical
21                      bw373u86                     BW373U86                     bw373u86          alias
22               BW373U86*******                     BW373U86                     bw373u86      canonical
23                     bemegride                    Bemegride                    bemegride          alias
24                     Bemegride                    Bemegride                    bemegride      canonical
25                   bethanechol                  Bethanechol                  bethanechol          alias
26                   Bethanechol                  Bethanechol                  bethanechol      canonical
27                   bicuculline                  Bicuculline                  bicuculline          alias
28                   Bicuculline                  Bicuculline                  bicuculline      canonical
29                     bupropion                    Bupropion                    bupropion          alias
30                     Bupropion                    Bupropion                    bupropion      canonical
31                      caffeine                     Caffeine                     caffeine          alias
32                      Caffeine                     Caffeine                     caffeine      canonical
33                     carbachol                    Carbachol                    carbachol          alias
34                     Carbachol                    Carbachol                    carbachol      canonical
35                chlorpromazine               Chlorpromazine               chlorpromazine          alias
36                Chlorpromazine               Chlorpromazine               chlorpromazine      canonical
37                      cis acpd                     Cis-ACPD                     cis acpd          alias
38                       cisacpd                     Cis-ACPD                      cisacpd          alias
39                    Cis-ACPD**                     Cis-ACPD                     cis acpd      canonical
40                     cisplatin                    Cisplatin                    cisplatin          alias
41                     Cisplatin                    Cisplatin                    cisplatin      canonical
42                  clomipramine                 Clomipramine                 clomipramine          alias
43                  Clomipramine                 Clomipramine                 clomipramine      canonical
44                     clonidine                    Clonidine                    clonidine          alias
45                     Clonidine                    Clonidine                    clonidine      canonical
46                     clozapine                    Clozapine                    clozapine          alias
47                     Clozapine                    Clozapine                    clozapine      canonical
48                       cocaine                      Cocaine                      cocaine          alias
49                       Cocaine                      Cocaine                      cocaine      canonical
50                          dmcm                         DMCM                         dmcm          alias
51                         DMCM*                         DMCM                         dmcm      canonical
52                  desipiramine                 Desipiramine                 desipiramine          alias
53                   desipramine                 Desipiramine                  desipramine          alias
54                  Desipiramine                 Desipiramine                 desipiramine      canonical
55                   domoic acid                  Domoic acid                  domoic acid          alias
56                   Domoic acid                  Domoic acid                  domoic acid      canonical
57                     donepezil                    Donepezil                    donepezil          alias
58                     Donepezil                    Donepezil                    donepezil      canonical
59                   emetic drug                      Emetine                  emetic drug          alias
60                       emetine                      Emetine                      emetine          alias
61                       Emetine                      Emetine                      emetine      canonical
62                       ethanol                      Ethanol                      ethanol          alias
63                       Ethanol                      Ethanol                      ethanol      canonical
64                      fentanyl                     Fentanyl                     fentanyl          alias
65                      Fentanyl                     Fentanyl                     fentanyl      canonical
66                      gabazine                     Gabazine                     gabazine          alias
67                      Gabazine                     Gabazine                     gabazine      canonical
68                   galantamine                  Galantamine                  galantamine          alias
69                   Galantamine                  Galantamine                  galantamine      canonical
70                   kainic acid                  Kainic acid                  kainic acid          alias
71                   Kainic acid                  Kainic acid                  kainic acid      canonical
72                      ketamine                     Ketamine                     ketamine          alias
73                      Ketamine                     Ketamine                     ketamine      canonical
74                  ketoconazole                 Ketoconazole                 ketoconazole          alias
75                  ketoconozole                 Ketoconazole                 ketoconozole          alias
76                  Ketoconazole                 Ketoconazole                 ketoconazole      canonical
77                   maprotiline                  Maprotiline                  maprotiline          alias
78                   Maprotiline                  Maprotiline                  maprotiline      canonical
79                    meperidine                   Meperidine                   meperidine          alias
80                     pethidine                   Meperidine                    pethidine          alias
81                    Meperidine                   Meperidine                   meperidine      canonical
82                   mizolastine                  Mizolastine                  mizolastine          alias
83                   Mizolastine                  Mizolastine                  mizolastine      canonical
84                      morphine                     Morphine                     morphine          alias
85                      Morphine                     Morphine                     morphine      canonical
86                     muscarine                    Muscarine                    muscarine          alias
87                     Muscarine                    Muscarine                    muscarine      canonical
88          n methyl d aspartate         N-methyl-D-aspartate         n methyl d aspartate          alias
89                          nmda         N-methyl-D-aspartate                         nmda          alias
90          N-methyl-D-aspartate         N-methyl-D-aspartate         n methyl d aspartate      canonical
91                   neostigmine                  Neostigmine                  neostigmine          alias
92                   Neostigmine                  Neostigmine                  neostigmine      canonical
93                   nomifensine                  Nomifensine                  nomifensine          alias
94                   Nomifensine                  Nomifensine                  nomifensine      canonical
95                    olanzapine                   Olanzapine                   olanzapine          alias
96                    Olanzapine                   Olanzapine                   olanzapine      canonical
97                  oxotremorine                 Oxotremorine                 oxotremorine          alias
98                  Oxotremorine                 Oxotremorine                 oxotremorine      canonical
99                    pf06767832                   PF06767832                   pf06767832          alias
100               PF06767832****                   PF06767832                   pf06767832      canonical
101                 paraxanthine                 Paraxanthine                 paraxanthine          alias
102                 Paraxanthine                 Paraxanthine                 paraxanthine      canonical
103           pentylenetetrazole           Pentylenetetrazole           pentylenetetrazole          alias
104                          ptz           Pentylenetetrazole                          ptz          alias
105           Pentylenetetrazole           Pentylenetetrazole           pentylenetetrazole      canonical
106                   phenserine                   Phenserine                   phenserine          alias
107                   Phenserine                   Phenserine                   phenserine      canonical
108                phencyclidine                 Phenyclidine                phencyclidine          alias
109                 Phenyclidine                 Phenyclidine                 phenyclidine      canonical
110                physostigmine                Physostigmine                physostigmine          alias
111     physostigmine salicylate                Physostigmine     physostigmine salicylate          alias
112                Physostigmine                Physostigmine                physostigmine      canonical
113                   picrotoxin                   Picrotoxin                   picrotoxin          alias
114                   Picrotoxin                   Picrotoxin                   picrotoxin      canonical
115                  pilocarpine                  Pilocarpine                  pilocarpine          alias
116                  Pilocarpine                  Pilocarpine                  pilocarpine      canonical
117                protriptyline                Protriptyline                protriptyline          alias
118                Protriptyline                Protriptyline                protriptyline      canonical
119                      quinine                  Quinine HCl                      quinine          alias
120                  quinine hcl                  Quinine HCl                  quinine hcl          alias
121                  Quinine HCl                  Quinine HCl                  quinine hcl      canonical
122                  risperidone                  Risperidone                  risperidone          alias
123                  Risperidone                  Risperidone                  risperidone      canonical
124                     rolipram                     Rolipram                     rolipram          alias
125                     Rolipram                     Rolipram                     rolipram      canonical
126                     sb205607                     SB205607                     sb205607          alias
127               SB205607******                     SB205607                     sb205607      canonical
128                        snc80                        SNC80                        snc80          alias
129                   SNC80*****                        SNC80                        snc80      canonical
130                   strychnine                   Strychnine                   strychnine          alias
131                   Strychnine                   Strychnine                   strychnine      canonical
132                      tacrine                      Tacrine                      tacrine          alias
133                      Tacrine                      Tacrine                      tacrine      canonical
134  tetraethylammonium chloride        Tetraethylammonium Cl  tetraethylammonium chloride          alias
135        tetraethylammonium cl        Tetraethylammonium Cl        tetraethylammonium cl          alias
136        Tetraethylammonium Cl        Tetraethylammonium Cl        tetraethylammonium cl      canonical
137                  theobromine                  Theobromine                  theobromine          alias
138                  Theobromine                  Theobromine                  theobromine      canonical
139                 theophylline                 Theophylline                 theophylline          alias
140                 Theophylline                 Theophylline                 theophylline      canonical
141                        xe991                        XE991                        xe991          alias
142                     XE991***                        XE991                        xe991      canonical
143                    yohimbine                    Yohimbine                    yohimbine          alias
144                    Yohimbine                    Yohimbine                    yohimbine      canonical

In [3]:
mechanism_alias_df = build_mechanism_of_action_alias_map()
display(mechanism_alias_df)

                                                mechanism_of_action                           mechanism_of_action_mnemonic
0                                             Alkaloid antimalarial                                  Alkaloid_Antimalarial
1                                            Alkaloid antiprotozoal                                 Alkaloid_Antiprotozoal
2                                     Antibiotic (sulfonamide-like)                             SulfonamideLike_Antibiotic
3                                         Cytochrome P450 inhibitor                                       CYP450_Inhibitor
4                  D1/2/3/4R/a1/2R/H1R/mACh1/2R/5-HT1/2R antagonism                   D1_D2_D3_D4R_MultiReceptorAntagonist
5                                             D1/2R/5-HT/aR agonism                                 D1_D2R_5HTR_aR_Agonist
6                           D1/2R/a1/2R/H1R/mAChR/5-HT2R antagonism                         D1_D2R_MultiReceptorAntagonist
7                             D2R/a1/2R/H1R/mAChR/5-HT2R antagonism                            D2R_MultiReceptorAntagonist
8                               D2R/a1R/H1R/mAChR/5-HT2R antagonism                            D2R_MultiReceptorAntagonist
9                                     DA/NA/5-HT reuptake inhibiton                         DAT_NET_SERT_ReuptakeInhibitor
10          DA/NA/5-HT reuptake inhibiton and Na2+ channel blockade        DAT_NET_SERT_ReuptakeInhibitor_NaChannelBlocker
11                               DNA cross linking chemotherapeutic                      DNA_CrossLinking_Chemotherapeutic
12                                                GABAAR antagonism                                      GABAAR_Antagonist
13                            GABAAR negative allosteric modulation                     GABAAR_NegativeAllostericModulator
14                            GABAAR positIve allosteric modulation                     GABAAR_PositiveAllostericModulator
15                                                  GlyR antagonism                                        GlyR_Antagonist
16                                                   H1R antagonism                                         H1R_Antagonist
17                                                   KAR activation                                         KAR_Activation
18                                      Kv7 (KCNQ) channel blockade                                            Kv7_Blocker
19                                       M1 selective mACHR agonist                             M1_mAChR_Agonist_Selective
20   NA reuptake inhibitor (weak 5-HT), mAChR, a1/2R/H1R antagonism  NET_ReuptakeInhibitor_Weak5HT_MultiReceptorAntagonist
21             NA/5-HT reuptake inhibitor, a1R/H1R/mAChR antagonism     NET_SERT_ReuptakeInhibitor_MultiReceptorAntagonist
22   NA/5-HT reuptake inhibitor,5-HT2R/a1R/DAR/H1R/mAChR antagonism     NET_SERT_ReuptakeInhibitor_MultiReceptorAntagonist
23  NA/5-HT reuptake inhibitor,5-HTR/a1R/DAR/H1/2R/mAChR antagonism     NET_SERT_ReuptakeInhibitor_MultiReceptorAntagonist
24      NA/5-HT reuptake inhibitor,5-HTR/a1R/H1/2R/mAChR antagonism     NET_SERT_ReuptakeInhibitor_MultiReceptorAntagonist
25        NA/5-HT reuptake inhibitor,DAR/5-HTR/a1/2R/H1R antagonism     NET_SERT_ReuptakeInhibitor_MultiReceptorAntagonist
26                                        NA/DA reuptake inhibition                              NET_DAT_ReuptakeInhibitor
27                                                 NMDAR activation                                       NMDAR_Activation
28                                                 NMDAR antagonism                                       NMDAR_Antagonist
29                                        Non-selective Kv blockade                                Kv_Blocker_NonSelective
30                                 P1 antagonism and PDE inhibition                            P1_Antagonist_PDE_Inhibitor
31                                                 PDE-4 inhibition                                         PDE4_Inhibitor
32                                       Reversible AChE inhibition                              AChE_Inhibitor_Reversible
33                  Reversible AChE inhibition (no BBB penetration)                        AChE_Inhibitor_Reversible_NoBBB
34                                             a2R agonism (in CNS)                                        a2R_Agonist_CNS
35                                                   a2R antagonism                                         a2R_Antagonist
36                                    mAChR agonism (non selective)                             mAChR_Agonist_NonSelective
37                                          mAChR and nAChR agonism                                    mAChR_nAChR_Agonist
38                                                δ-opioidR agonism                                            DOR_Agonist
39                                               μ-opioid R agonism                                            MOR_Agonist
40                                                μ-opioidR agonism                                            MOR_Agonist
41                                           μ-δ-opioidR activation                                     MOR_DOR_Activation

In [4]:
classification_df = load_compound_classification()
display(classification_df)

                       compound                            compound_class                                    mechanism_of_action
0                   Bicuculline                                Analeptics                                      GABAAR_Antagonist
1            Pentylenetetrazole                                Analeptics                                      GABAAR_Antagonist
2                    Picrotoxin                                Analeptics                                      GABAAR_Antagonist
3                     Bemegride                                Analeptics                                      GABAAR_Antagonist
4                      Gabazine                                Analeptics                                      GABAAR_Antagonist
5                          DMCM                                Analeptics                     GABAAR_NegativeAllostericModulator
6                    Strychnine                        Glycine antagonist                                        GlyR_Antagonist
7                   Kainic acid                        Glutamate agonists                                         KAR_Activation
8          N-methyl-D-aspartate                        Glutamate agonists                                       NMDAR_Activation
9                   Domoic acid                        Glutamate agonists                                         KAR_Activation
10                     Cis-ACPD                        Glutamate agonists                                       NMDAR_Activation
11  (RS)-(Tetrazol-5-yl)glycine                        Glutamate agonists                                       NMDAR_Activation
12              4-aminopyridine                       K+ channel blockers                                Kv_Blocker_NonSelective
13        Tetraethylammonium Cl                       K+ channel blockers                                Kv_Blocker_NonSelective
14                        XE991                       K+ channel blockers                                            Kv7_Blocker
15                  Pilocarpine                       Muscarinic agonists                             mAChR_Agonist_NonSelective
16                  Bethanechol                       Muscarinic agonists                             mAChR_Agonist_NonSelective
17                    Carbachol                       Muscarinic agonists                                    mAChR_nAChR_Agonist
18                 Oxotremorine                       Muscarinic agonists                                    mAChR_nAChR_Agonist
19                    Muscarine                       Muscarinic agonists                             mAChR_Agonist_NonSelective
20                   PF06767832                       Muscarinic agonists                             M1_mAChR_Agonist_Selective
21                     BW373U86                         Opioid analgesics                                            DOR_Agonist
22                        SNC80                         Opioid analgesics                                            DOR_Agonist
23                     Fentanyl                         Opioid analgesics                                            MOR_Agonist
24                   Meperidine                         Opioid analgesics                                            MOR_Agonist
25                     Morphine                         Opioid analgesics                                     MOR_DOR_Activation
26                     SB205607                         Opioid analgesics                                            DOR_Agonist
27                    Donepezil                   ACh esterase inhibitors                              AChE_Inhibitor_Reversible
28                Physostigmine                   ACh esterase inhibitors                              AChE_Inhibitor_Reversible
29                      Tacrine                   ACh esterase inhibitors                              AChE_Inhibitor_Reversible
30                  Galantamine                   ACh esterase inhibitors                              AChE_Inhibitor_Reversible
31                  Neostigmine                   ACh esterase inhibitors                        AChE_Inhibitor_Reversible_NoBBB
32                   Phenserine                   ACh esterase inhibitors                              AChE_Inhibitor_Reversible
33                    Bupropion                       NDRI Antidepressant                              NET_DAT_ReuptakeInhibitor
34                  Nomifensine                       NDRI Antidepressant                              NET_DAT_ReuptakeInhibitor
35                  Maprotiline                Tetracyclic Antidepressant  NET_ReuptakeInhibitor_Weak5HT_MultiReceptorAntagonist
36                    Amoxapine                 Tricyclic antidepressants     NET_SERT_ReuptakeInhibitor_MultiReceptorAntagonist
37                Amitriptyline                 Tricyclic antidepressants     NET_SERT_ReuptakeInhibitor_MultiReceptorAntagonist
38                 Clomipramine                 Tricyclic antidepressants     NET_SERT_ReuptakeInhibitor_MultiReceptorAntagonist
39                 Desipiramine                 Tricyclic antidepressants     NET_SERT_ReuptakeInhibitor_MultiReceptorAntagonist
40                Protriptyline                 Tricyclic antidepressants     NET_SERT_ReuptakeInhibitor_MultiReceptorAntagonist
41               Chlorpromazine               Phenothiazine antipsychotic                   D1_D2_D3_D4R_MultiReceptorAntagonist
42                    Clozapine                   Atypical antipsychotics                         D1_D2R_MultiReceptorAntagonist
43                   Olanzapine                   Atypical antipsychotics                            D2R_MultiReceptorAntagonist
44                  Risperidone                   Atypical antipsychotics                            D2R_MultiReceptorAntagonist
45                Aminophylline                Methylxanthine derivatives                            P1_Antagonist_PDE_Inhibitor
46                 Theophylline                Methylxanthine derivatives                            P1_Antagonist_PDE_Inhibitor
47                     Caffeine                Methylxanthine derivatives                            P1_Antagonist_PDE_Inhibitor
48                  Theobromine                Methylxanthine derivatives                            P1_Antagonist_PDE_Inhibitor
49                 Paraxanthine                Methylxanthine derivatives                            P1_Antagonist_PDE_Inhibitor
50                      Cocaine                             Illicit drugs        DAT_NET_SERT_ReuptakeInhibitor_NaChannelBlocker
51                  Amphetamine                             Illicit drugs                         DAT_NET_SERT_ReuptakeInhibitor
52                 Phenyclidine                             Illicit drugs                                       NMDAR_Antagonist
53                  Apomorphine   Mixed classes, unclear link to seizures                                 D1_D2R_5HTR_aR_Agonist
54                      Ethanol   Mixed classes, unclear link to seizures                     GABAAR_PositiveAllostericModulator
55                     Rolipram   Mixed classes, unclear link to seizures                                         PDE4_Inhibitor
56                    Yohimbine   Mixed classes, unclear link to seizures                                         a2R_Antagonist
57        4-Aminophenyl sulfone  Mixed classes, no known link to seizures                             SulfonamideLike_Antibiotic
58                    Cisplatin  Mixed classes, no known link to seizures                      DNA_CrossLinking_Chemotherapeutic
59                    Clonidine  Mixed classes, no known link to seizures                                        a2R_Agonist_CNS
60                      Emetine  Mixed classes, no known link to seizures                                 Alkaloid_Antiprotozoal
61                     Ketamine  Mixed classes, no known link to seizures                                       NMDAR_Antagonist
62                 Ketoconazole  Mixed classes, no known link to seizures                                       CYP450_Inhibitor
63                  Mizolastine  Mixed classes, no known link to seizures                                         H1R_Antagonist
64                  Quinine HCl  Mixed classes, no known link to seizures                                  Alkaloid_Antimalarial

In [5]:
class_counts = classification_df["compound_class"].value_counts(dropna=False).rename_axis("compound_class").reset_index(name="n_compounds")
moa_counts = classification_df["mechanism_of_action"].value_counts(dropna=False).rename_axis("mechanism_of_action").reset_index(name="n_compounds")

display(class_counts)
display(moa_counts)

                              compound_class  n_compounds
0   Mixed classes, no known link to seizures            8
1                                 Analeptics            6
2                        Muscarinic agonists            6
3                          Opioid analgesics            6
4                    ACh esterase inhibitors            6
5                         Glutamate agonists            5
6                  Tricyclic antidepressants            5
7                 Methylxanthine derivatives            5
8    Mixed classes, unclear link to seizures            4
9                        K+ channel blockers            3
10                   Atypical antipsychotics            3
11                             Illicit drugs            3
12                       NDRI Antidepressant            2
13                        Glycine antagonist            1
14                Tetracyclic Antidepressant            1
15               Phenothiazine antipsychotic            1

                                      mechanism_of_action  n_compounds
0                                       GABAAR_Antagonist            5
1                               AChE_Inhibitor_Reversible            5
2      NET_SERT_ReuptakeInhibitor_MultiReceptorAntagonist            5
3                             P1_Antagonist_PDE_Inhibitor            5
4                                        NMDAR_Activation            3
5                              mAChR_Agonist_NonSelective            3
6                                             DOR_Agonist            3
7                                          KAR_Activation            2
8                                 Kv_Blocker_NonSelective            2
9                                     mAChR_nAChR_Agonist            2
10                                            MOR_Agonist            2
11                              NET_DAT_ReuptakeInhibitor            2
12                            D2R_MultiReceptorAntagonist            2
13                                       NMDAR_Antagonist            2
14                     GABAAR_NegativeAllostericModulator            1
15                                        GlyR_Antagonist            1
16                                            Kv7_Blocker            1
17                             M1_mAChR_Agonist_Selective            1
18                                     MOR_DOR_Activation            1
19                        AChE_Inhibitor_Reversible_NoBBB            1
20  NET_ReuptakeInhibitor_Weak5HT_MultiReceptorAntagonist            1
21                   D1_D2_D3_D4R_MultiReceptorAntagonist            1
22                         D1_D2R_MultiReceptorAntagonist            1
23        DAT_NET_SERT_ReuptakeInhibitor_NaChannelBlocker            1
24                         DAT_NET_SERT_ReuptakeInhibitor            1
25                                 D1_D2R_5HTR_aR_Agonist            1
26                     GABAAR_PositiveAllostericModulator            1
27                                         PDE4_Inhibitor            1
28                                         a2R_Antagonist            1
29                             SulfonamideLike_Antibiotic            1
30                      DNA_CrossLinking_Chemotherapeutic            1
31                                        a2R_Agonist_CNS            1
32                                 Alkaloid_Antiprotozoal            1
33                                       CYP450_Inhibitor            1
34                                         H1R_Antagonist            1
35                                  Alkaloid_Antimalarial            1